name: Scala Steward

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  scala-steward:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11]
    name: Scala Steward (Java ${{ matrix.java-version }})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: temurin

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Run Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-app-id: ${{ secrets.SCALA_STEWARD_GITHUB_APP_ID }}
          github-app-installation-id: ${{ secrets.SCALA_STEWARD_GITHUB_APP_INSTALLATION_ID }}
          github-app-key: ${{ secrets.SCALA_STEWARD_GITHUB_APP_PRIVATE_KEY }}
          github-app-auth-only: true
